### ISSUE TITLE
lib crashes on log flush

### ISSUE THREAD

**Issue by andrehp** [statsig-io/node-js-server-sdk#15]
Hello all,

We've tried updating the statsig lib in our application to 4.20.0, but we faced a crash in the library, the same crash doesn't happen on 4.19.0

```
application/node_modules/statsig-node/dist/LogEventProcessor.js:95
                if (this.queue.length === 0) {
                               ^
TypeError: Cannot read properties of undefined (reading 'length')
    at Timeout.<anonymous> (application/node_modules/statsig-node/dist/LogEventProcessor.js:95:32)
    at step (application/node_modules/statsig-node/dist/LogEventProcessor.js:33:23)
    at Object.next (application/node_modules/statsig-node/dist/LogEventProcessor.js:14:53)
    at application/node_modules/statsig-node/dist/LogEventProcessor.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (application/node_modules/statsig-node/dist/LogEventProcessor.js:4:12)
    at Timeout.LogEventProcessor.flush [as _onTimeout] (application/node_modules/statsig-node/dist/LogEventProcessor.js:91:16)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

```

**Comment by tore-statsig** [comment]
We're looking in to this

**Comment by tore-statsig** [comment]
Fixed in https://github.com/statsig-io/node-js-server-sdk/pull/16

and published in https://www.npmjs.com/package/statsig-node/v/4.20.1
