### ISSUE TITLE
Allow for custom logger implementation

### ISSUE THREAD

**Issue by ryanquinn3** [statsig-io/node-js-server-sdk#23]
Hey Statsig team, 

I was hoping you all would be open to allowing the node sdk to accept a custom logger implementation instead of hardcoding the use of `console.{*}`. In our case, we have some production tooling that assumes all of our server logs are emitted in json format and occasionally we are seeing some logs such as `Syncing the server SDK with statsig has failed for  130000ms. ...` emitted from the statsig sdk which gives our tooling a hard time. 

An example of a solid interface would be [slacks node sdk](https://slack.dev/node-slack-sdk/web-api#logging). 

Thanks!

**Comment by kenny-statsig** [comment]
Thanks for the feedback! We do have plans to add support for a custom logger in the Node JS SDK. We are currently prioritizing other SDKs, but i'll add the node SDK to the list. As a rough estimate, i'd say we'll have this out by mid May.

**Comment by Raynos** [comment]
I am also looking for this, i just saw an error stack trace on stdout and was really suprised its not silent by default.

Is there a silent option I can pass in ? 

```ts
$ SERVICE_NAME=testlol pnpm bob-tsm ./src/index.ts 
$ node --require=bob-tsm --loader=bob-tsm --enable-source-maps ./src/index.ts
StatsigLocalModeNetworkError: No network requests in localMode
    at new StatsigLocalModeNetworkError (/home/raynos/soundxyz/code/node_modules/.pnpm/statsig-node@5.5.0/node_modules/statsig-node/dist/Errors.js:52:28)
    at StatsigFetcher.post (/home/raynos/soundxyz/code/node_modules/.pnpm/statsig-node@5.5.0/node_modules/statsig-node/dist/utils/StatsigFetcher.js:29:35)
    at SpecStore.<anonymous> (/home/raynos/soundxyz/code/node_modules/.pnpm/statsig-node@5.5.0/node_modules/statsig-node/dist/SpecStore.js:643:59)
    at step (/home/raynos/soundxyz/code/node_modules/.pnpm/statsig-node@5.5.0/node_modules/statsig-node/dist/SpecStore.js:33:23)
    at Object.next (/home/raynos/soundxyz/code/node_modules/.pnpm/statsig-node@5.5.0/node_modules/statsig-node/dist/SpecStore.js:14:53)
    at /home/raynos/soundxyz/code/node_modules/.pnpm/statsig-node@5.5.0/node_modules/statsig-node/dist/SpecStore.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/raynos/soundxyz/code/node_modules/.pnpm/statsig-node@5.5.0/node_modules/statsig-node/dist/SpecStore.js:4:12)
    at SpecStore.syncIdListsFromNetwork (/home/raynos/soundxyz/code/node_modules/.pnpm/statsig-node@5.5.0/node_modules/statsig-node/dist/SpecStore.js:631:16)
    at SpecStore.<anonymous> (/home/raynos/soundxyz/code/node_modules/.pnpm/statsig-node@5.5.0/node_modules/statsig-node/dist/SpecStore.js:217:55)
raynos at raynos-Precision-5530  
```

**Comment by Raynos** [comment]
Fixed in https://github.com/statsig-io/node-js-server-sdk/pull/26

**Comment by kenny-statsig** [comment]
Added in v5.6.0
